"""
reporter.py – Generate diagnostic reports in plain-text and HTML formats.
"""

from __future__ import annotations

import html
import json
from datetime import datetime
from pathlib import Path

from .diagnostics import DiagnosticReport, CheckResult

STATUS_EMOJI = {
    "ok": "✅",
    "warning": "⚠️ ",
    "error": "❌",
    "info": "ℹ️ ",
    "skipped": "⏭️ ",
}

STATUS_COLOR = {
    "ok": "#2ecc71",
    "warning": "#f39c12",
    "error": "#e74c3c",
    "info": "#3498db",
    "skipped": "#95a5a6",
}


# ---------------------------------------------------------------------------
# Plain-text
# ---------------------------------------------------------------------------

def to_text(report: DiagnosticReport) -> str:
    lines = [
        "=" * 70,
        "  BlueScreenHelp — Diagnostic Report",
        f"  Generated : {report.timestamp}",
        f"  Host      : {report.hostname}",
        f"  OS        : {report.os_info}",
        "=" * 70,
        "",
    ]
    for check in report.checks:
        emoji = STATUS_EMOJI.get(check.status, "?")
        lines.append(f"{emoji}  {check.name}")
        lines.append(f"     Status  : {check.status.upper()}")
        lines.append(f"     Summary : {check.summary}")
        for d in check.details:
            lines.append(f"       • {d}")
        lines.append("")

    # Summary counts
    counts: dict[str, int] = {}
    for c in report.checks:
        counts[c.status] = counts.get(c.status, 0) + 1

    lines.append("-" * 70)
    lines.append("Summary:")
    for status, count in sorted(counts.items()):
        lines.append(f"  {STATUS_EMOJI.get(status, '?')} {status.upper()}: {count}")
    lines.append("=" * 70)
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------

def _check_html(check: CheckResult) -> str:
    color = STATUS_COLOR.get(check.status, "#ccc")
    emoji = STATUS_EMOJI.get(check.status, "?")
    detail_html = ""
    if check.details:
        items = "".join(f"<li>{html.escape(d)}</li>" for d in check.details)
        detail_html = f"<ul>{items}</ul>"
    return f"""
    <div class="check" style="border-left: 5px solid {color};">
      <h3>{emoji} {html.escape(check.name)}
        <span class="badge" style="background:{color};">{check.status.upper()}</span>
      </h3>
      <p>{html.escape(check.summary)}</p>
      {detail_html}
    </div>"""


def to_html(report: DiagnosticReport) -> str:
    checks_html = "\n".join(_check_html(c) for c in report.checks)

    counts: dict[str, int] = {}
    for c in report.checks:
        counts[c.status] = counts.get(c.status, 0) + 1

    summary_badges = " ".join(
        f'<span class="badge" style="background:{STATUS_COLOR.get(s,"#ccc")};">'
        f'{STATUS_EMOJI.get(s,"?")} {s.upper()}: {n}</span>'
        for s, n in sorted(counts.items())
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>BlueScreenHelp — Diagnostic Report</title>
  <style>
    body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #1a1a2e; color: #eee;
            margin: 0; padding: 20px; }}
    h1 {{ color: #00bcd4; border-bottom: 2px solid #00bcd4; padding-bottom: 10px; }}
    .meta {{ color: #aaa; font-size: 0.9em; margin-bottom: 20px; }}
    .check {{ background: #16213e; border-radius: 6px; padding: 14px 18px;
              margin-bottom: 14px; }}
    .check h3 {{ margin: 0 0 6px; font-size: 1.05em; }}
    .check p {{ margin: 4px 0; color: #ccc; }}
    .check ul {{ margin: 6px 0; padding-left: 20px; color: #bbb; }}
    .badge {{ display: inline-block; padding: 2px 8px; border-radius: 12px;
              font-size: 0.75em; font-weight: bold; color: #fff; margin-left: 8px;
              vertical-align: middle; }}
    .summary {{ margin-top: 30px; padding: 16px; background: #0f3460;
                border-radius: 8px; }}
    footer {{ margin-top: 30px; font-size: 0.8em; color: #666; text-align: center; }}
  </style>
</head>
<body>
  <h1>🖥 BlueScreenHelp — Diagnostic Report</h1>
  <div class="meta">
    <strong>Generated:</strong> {html.escape(report.timestamp)}<br>
    <strong>Host:</strong> {html.escape(report.hostname)}<br>
    <strong>OS:</strong> {html.escape(report.os_info)}
  </div>
  {checks_html}
  <div class="summary">
    <strong>Summary:</strong> {summary_badges}
  </div>
  <footer>Generated by BlueScreenHelp Agent · github.com/Unwrenchable/BlueScreenHelp</footer>
</body>
</html>"""


# ---------------------------------------------------------------------------
# JSON
# ---------------------------------------------------------------------------

def to_json(report: DiagnosticReport) -> str:
    return json.dumps(report.as_dict(), indent=2, ensure_ascii=False)


# ---------------------------------------------------------------------------
# Save helper
# ---------------------------------------------------------------------------

def save_report(report: DiagnosticReport, output_dir: Path | None = None,
                formats: list[str] | None = None) -> dict[str, Path]:
    """
    Save report in requested formats.  Returns {format: path}.
    formats defaults to ["txt", "html"].
    """
    formats = formats or ["txt", "html"]
    output_dir = output_dir or Path.cwd()
    output_dir.mkdir(parents=True, exist_ok=True)

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    base = output_dir / f"bsh_report_{ts}"
    saved: dict[str, Path] = {}

    if "txt" in formats:
        p = base.with_suffix(".txt")
        p.write_text(to_text(report), encoding="utf-8")
        saved["txt"] = p
    if "html" in formats:
        p = base.with_suffix(".html")
        p.write_text(to_html(report), encoding="utf-8")
        saved["html"] = p
    if "json" in formats:
        p = base.with_suffix(".json")
        p.write_text(to_json(report), encoding="utf-8")
        saved["json"] = p

    return saved
